"""Tau extension system: discovery, loading, and the extension API."""

from tau_coding.extensions.api import (
    AGENT_EVENT_TYPES,
    AGENT_EVENT_WILDCARD,
    LIFECYCLE_EVENT_TYPES,
    ExtensionAPI,
    ExtensionCommandContext,
    ExtensionCommandHandler,
    ExtensionContext,
    ExtensionError,
    ExtensionHandler,
    InputEvent,
    InputHookResult,
    NullUiBridge,
    SessionShutdownEvent,
    SessionStartEvent,
    ToolCallHookEvent,
    ToolCallHookResult,
    ToolResultHookEvent,
    ToolResultHookResult,
    UiBridge,
)
from tau_coding.extensions.loader import (
    DiscoveredExtension,
    ExtensionLoadResult,
    LoadedExtension,
    discover_extensions,
    extension_dirs,
    load_extensions,
)
from tau_coding.extensions.runtime import (
    BoundSession,
    ExtensionRuntime,
    InputHookOutcome,
)

__all__ = [
    "AGENT_EVENT_TYPES",
    "AGENT_EVENT_WILDCARD",
    "LIFECYCLE_EVENT_TYPES",
    "BoundSession",
    "DiscoveredExtension",
    "ExtensionAPI",
    "ExtensionCommandContext",
    "ExtensionCommandHandler",
    "ExtensionContext",
    "ExtensionError",
    "ExtensionHandler",
    "ExtensionLoadResult",
    "ExtensionRuntime",
    "InputEvent",
    "InputHookOutcome",
    "InputHookResult",
    "LoadedExtension",
    "NullUiBridge",
    "SessionShutdownEvent",
    "SessionStartEvent",
    "ToolCallHookEvent",
    "ToolCallHookResult",
    "ToolResultHookEvent",
    "ToolResultHookResult",
    "UiBridge",
    "discover_extensions",
    "extension_dirs",
    "load_extensions",
]
